%YAML 1.1
---
datasets:
    # Longitudinal object
    d0_d30:
        # Replace the paths below with the paths to each object and config file
        # The object should be a .rds file containing a Seurat object.
        object: ./Seurat_Objects/longitudinal_samples_20211025.rds
        # The config file should be a .yaml file. The file is created using
        # the config app at /config_app.R.
        config: ./Seurat_Objects/d0-d30_config_with_designated_assays.yaml
    # Pheresis object
    pheresis_samples:
        object: ./Seurat_Objects/aml_bmmc_totalvi_20211206_slim1000.rds
        config: ./Seurat_Objects/AML_TotalVI_config_with_dataset_description.yaml

#RSTUDIO_PANDOC: "/Applications/RStudio.app/Contents/MacOS/pandoc"
