config_version: 0.9.3
object_class: Seurat
is_HDF5SummarizedExperiment: no
HDF5_prefix: ''
label: AML Reference Dataset
description: |-
  AML reference dataset from Triana et al. 2021 (see https://doi.org/10.1038/s41590-021-01059-0). The dataset includes a pheresis and a bone marrow sample from a single young healthy donor. A panel of 462 genes is included in the dataset, along with 197 surface protein markers. A UMAP projection based on gene expression was
  computed from the original Seurat object downloaded from Figshare (https://figshare.com/articles/dataset/Expression_of_197_surface_markers_and_462_mRNAs_in_15281_cells_from_blood_and_bone_marrow_from_a_young_healthy_donor/13398065/2).
preview:
  type: dimplot
  plot_settings:
    group_by: condensed_cell_type
    split_by: none
    reduction: umap
    ncol: 1
    label: yes
    legend: yes
assays:
  RNA:
    assay: RNA
    key: rna_
    suffix_human: ''
    dropdown_title: Gene
  AB:
    assay: AB
    key: ab_
    suffix_human: ''
    dropdown_title: Surface Protein
other_assay_options:
  genes_assay: RNA
  adt_assay: none
include_numeric_metadata: yes
metadata:
  condensed_cell_type:
    meta_colname: condensed_cell_type
    label: Cell Type
    description: 'Cell type calls from Triana et al., condensed into 10 high-level
      cell types. '
    groups: ~
  Batch:
    meta_colname: Batch
    label: Sample Type
    description: ''
    groups: ~
other_metadata_options:
  patient_colname: ~
reductions:
  umap:
    reduction: umap
    label: UMAP
  pca:
    reduction: pca
    label: PCA
adt_thresholds: ~
