# Auto-generated script produced using shinyApp::recordTest
app <- ShinyDriver$new("../../")
app$snapshotInit("correlations-tab-automated-test")

app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_hidden = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_plots-main_panel_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_plots-subset_panel_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_plots-violin-custom_refactor` = c("B Cells", "BM Monocytes", "CD4+ T Cells", "CD8+ T Cells", "Dendritic cells", "NK Cells", "PBMC Monocytes", "Plasma cells", "Plasmacytoid dendritic cells", "Primitive"), allowInputNoBinding_ = TRUE)
app$setInputs(`object_plots-dot-custom_refactor` = c("B Cells", "BM Monocytes", "CD4+ T Cells", "CD8+ T Cells", "Dendritic cells", "NK Cells", "PBMC Monocytes", "Plasma cells", "Plasmacytoid dendritic cells", "Primitive"), allowInputNoBinding_ = TRUE)
app$setInputs(`object_plots-ridge-custom_refactor` = character(0), allowInputNoBinding_ = TRUE)
app$setInputs(`object_plots-proportion-custom_refactor` = c("B Cells", "BM Monocytes", "CD4+ T Cells", "CD8+ T Cells", "Dendritic cells", "NK Cells", "PBMC Monocytes", "Plasma cells", "Plasmacytoid dendritic cells", "Primitive"), allowInputNoBinding_ = TRUE)

app$setInputs(navigator = "Gene Correlations")

app$setInputs(`object_corr-feature_selection` = "rna_MPO")
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = TRUE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = FALSE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-submit` = "click")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-main_panel_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-sidebar_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-corr_table_rows_selected` = 4, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-corr_table_row_last_clicked` = 4, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-corr_table_cell_clicked` = c("4", "0", "SELENOP"), allowInputNoBinding_ = TRUE, priority_ = "event")
app$snapshot()
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = TRUE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = "B Cells")
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = FALSE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-submit` = "click")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-main_panel_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-sidebar_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = TRUE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = character(0))
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = "NK Cells")
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = c("NK Cells", "PBMC Monocytes"))
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = c("NK Cells", "PBMC Monocytes", "Plasma cells"))
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = c("NK Cells", "PBMC Monocytes", "Plasma cells", "Plasmacytoid dendritic cells"))
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection` = c("NK Cells", "PBMC Monocytes", "Plasma cells", "Plasmacytoid dendritic cells", "Primitive"))
app$setInputs(`object_corr-subset_selections-condensed_cell_type_selection_open` = FALSE, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-submit` = "click")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(waiter_shown = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-main_panel_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-sidebar_waiter_hidden` = TRUE, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-corr_table_rows_selected` = 5, allowInputNoBinding_ = TRUE)
app$setInputs(`object_corr-corr_table_row_last_clicked` = 5, allowInputNoBinding_ = TRUE, priority_ = "event")
app$setInputs(`object_corr-corr_table_cell_clicked` = c("5", "0", "SELENOP"), allowInputNoBinding_ = TRUE, priority_ = "event")
app$snapshot()
